import type { CSSProperties } from 'react';

export const authStyles: Record<string, CSSProperties> = {
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  label: {
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: '.06em',
    textTransform: 'uppercase',
    color: 'var(--lp-muted)',
  },
  inputWrap: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  inputIcon: {
    position: 'absolute',
    left: 14,
    color: 'var(--lp-muted)',
    pointerEvents: 'none',
    display: 'inline-flex',
  },
  input: {
    width: '100%',
    border: '1px solid rgba(215, 209, 176, .18)',
    borderRadius: 14,
    background: 'rgba(17, 16, 15, .58)',
    color: 'var(--lp-text)',
    padding: '13px 16px 13px 42px',
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: '-.01em',
    boxShadow: 'inset 0 2px 8px rgba(17,16,15,.36), inset 0 1px 0 rgba(255,255,255,.04)',
  },
  passwordToggle: {
    position: 'absolute',
    right: 8,
    height: 32,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    padding: '0 10px',
    border: '1px solid var(--lp-glass-control-border-subtle)',
    background: 'var(--lp-glass-control-subtle)',
    color: 'var(--lp-text-soft)',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
    cursor: 'pointer',
    backdropFilter: 'blur(14px) saturate(1.08)',
    WebkitBackdropFilter: 'blur(14px) saturate(1.08)',
  },
  hint: {
    margin: 0,
    fontSize: 12,
    color: 'var(--lp-muted)',
    lineHeight: 1.5,
  },
  fieldRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: 14,
  },
  optionRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 4,
  },
  checkboxLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    color: 'var(--lp-text-soft)',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  checkbox: {
    width: 16,
    height: 16,
    accentColor: 'var(--lp-cream)',
    cursor: 'pointer',
  },
  link: {
    color: 'var(--lp-cream)',
    fontWeight: 700,
    textDecoration: 'none',
    fontSize: 13,
    cursor: 'pointer',
    background: 'transparent',
    border: 'none',
    padding: 0,
  },
  primaryButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    width: '100%',
    border: '1px solid var(--lp-glass-cream-border)',
    borderRadius: 14,
    padding: '14px 20px',
    background: 'var(--lp-cream)',
    color: 'var(--lp-bg-deep)',
    fontWeight: 800,
    fontSize: 14,
    letterSpacing: '-.01em',
    cursor: 'pointer',
    boxShadow: '0 4px 24px rgba(235, 230, 201, .2), 0 1px 3px rgba(235, 230, 201, .25)',
    transition: 'transform .15s ease, box-shadow .15s ease',
  },
  divider: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    margin: '6px 0',
    color: 'var(--lp-muted)',
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '.16em',
    textTransform: 'uppercase',
  },
  dividerLine: {
    flex: 1,
    height: 1,
    background: 'var(--lp-line)',
  },
  errorBanner: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 10,
    padding: '12px 14px',
    border: '1px solid rgba(224, 90, 79, .42)',
    borderRadius: 12,
    background: 'rgba(224, 90, 79, .12)',
    color: '#f1a39c',
    fontSize: 13,
    lineHeight: 1.5,
  },
  successBanner: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 10,
    padding: '12px 14px',
    border: '1px solid rgba(79, 166, 106, .42)',
    borderRadius: 12,
    background: 'rgba(79, 166, 106, .12)',
    color: '#9ed8b1',
    fontSize: 13,
    lineHeight: 1.5,
  },
  formHeader: {
    marginBottom: 18,
  },
  formTitle: {
    margin: 0,
    fontSize: 24,
    fontWeight: 900,
    letterSpacing: '-.03em',
    color: 'var(--lp-cream)',
  },
  formSubtitle: {
    margin: '6px 0 0',
    color: 'var(--lp-muted)',
    fontSize: 13.5,
    lineHeight: 1.55,
  },
};
